"""Create report and found item tables

Revision ID: e2b2e0a4c06d
Revises: 
Create Date: 2026-10-07 21:38:28.555834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b2e0a4c06d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('found_date', sa.Date(), nullable=False),
    sa.Column('found_time', sa.Time(), nullable=False),
    sa.Column('found_location', sa.String(length=200), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('storage_location', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_date', sa.Date(), nullable=False),
    sa.Column('notice_time', sa.Time(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chat_room_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_items')
    op.drop_table('found_items')
    # ### end Alembic commands ###
